apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-market
spec:
  replicas: 2
  selector:
    matchLabels:
      name: gateway-market
  template:
    metadata:
      labels:
        name: gateway-market
    spec:
      containers:
        - name: gateway-market-container
          image: gateway-market
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8880
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-market-service
spec:
  ports:
    - port: 8880
      name: "gateway-market"
      targetPort: 8880
      protocol: TCP
      #nodePort: 30088
  type: NodePort
  selector:
    name: gateway-market

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      name: gateway-proxy
  template:
    metadata:
      labels:
        name: gateway-proxy
    spec:
      containers:
        - name: gateway-proxy-container
          image: gateway-proxy
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
            - containerPort: 4433
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-proxy-service
spec:
  ports:
    - port: 8080
      name: "http"
      targetPort: 8080
      protocol: TCP
      nodePort: 30080
    - port: 4433
      name: "https"
      targetPort: 4433
      protocol: TCP
      nodePort: 30443
  type: NodePort
  selector:
    name: gateway-proxy
