FROM golang:alpine AS builder

LABEL stage=gobuidler

ENV GOPROXY https://goproxy.cn,direct
ENV GOOS linux
ENV GO111MODULE auto

WORKDIR /go/src/app

ADD go.mod .
ADD go.sum .
RUN go mod download
COPY . .
COPY conf/kubernetes  /app/etc/
COPY cert /app/cert

RUN go build -ldflags="-s -w" -o /app/gateway-proxy main.go

FROM alpine

ENV TZ Asia/Chongqing

WORKDIR /app

COPY --from=builder /app/gateway-proxy /app/gateway-proxy
COPY --from=builder /app/etc /app/etc
COPY --from=builder /app/cert /app/cert

CMD ["./gateway-proxy", "--config", "etc/","--kind","proxy"]
