definitions:
  controller.LoginSwagIn:
    properties:
      password:
        example: passwd
        type: string
      username:
        example: admin
        type: string
    required:
    - password
    - username
    type: object
  controller.Response:
    properties:
      code:
        type: integer
      data:
        type: string
      msg:
        type: string
    type: object
info:
  contact: {}
paths:
  /admin/login:
    post:
      consumes:
      - application/json
      description: 网关后台管理系统管理员登录
      operationId: /admin/login
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.LoginSwagIn'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/controller.Response'
      summary: admin_login
      tags:
      - admin接口
swagger: "2.0"
